hook.Add("AddToolMenuCategories", "TemperatureModCategory", function()
    spawnmenu.AddToolCategory("Utilities", "Temperature Mod", "Temperature Mod")
    spawnmenu.AddToolCategory("Main", "Temperature Mod", "Temperature Mod")
end)

hook.Add("PopulateToolMenu", "TemperatureModSettings", function()
    spawnmenu.AddToolMenuOption("Utilities", "Temperature Mod", "tempmodserver", "#tempmod.tempmod_servercategory", "", "", function(panel)
        panel:ClearControls()
        panel:Help("#tempmod.tempmod_serversideoptions")
        panel:Help("#tempmod.tempmod_temperature")
        panel:NumSlider("#tempmod.tempmod_normaltemperature", "tempmod_normal_temperature", 0, 500, 1)
        panel:ControlHelp("#tempmod.tempmod_normalobjecttemperature")
        panel:Help("#tempmod.tempmod_damagefromtemperature")
        panel:CheckBox("#tempmod.tempmod_propdamage", "tempmod_damageprops")
        panel:ControlHelp("#tempmod.tempmod_propdamagedesc")
        panel:NumSlider("#tempmod.tempmod_tempfordamage", "tempmod_tempfordamage", 50, 1000, 0)
        panel:ControlHelp("#tempmod.tempmod_tempfordamagedesc")

        panel:Help("#tempmod.tempmod_valuestitle")
		panel:NumSlider("#tempmod.tempmod_decreasevalue", "tempmod_tempdecrease_value", 0, 50, 0)
        panel:ControlHelp("#tempmod.tempmod_decreasevaluedesc")
        panel:NumSlider("#tempmod.tempmod_increasevalue", "tempmod_tempincrease_value", 3, 50, 1)
        panel:ControlHelp("#tempmod.tempmod_increasevaluedesc")
        panel:NumSlider("#tempmod.tempmod_spreadvalue", "tempmod_tempspread_value", 0.05, 0.1, 2)
        panel:ControlHelp("#tempmod.tempmod_spreadvaluedesc")

        panel:Help("#tempmod.tempmod_realismtitle")
		panel:CheckBox("#tempmod.tempmod.temperaturespread", "tempmod_tempspread")
        panel:ControlHelp("#tempmod.tempmod.temperaturespreaddesc")

        panel:Help("#tempmod.tempmod.time")
		panel:NumSlider("#tempmod.tempmod.timedecrease", "tempmod_tempdecrease_updatetime", 1, 60, 0)
        panel:ControlHelp("#tempmod.tempmod.timedecrease_help")

        panel:NumSlider("#tempmod.tempmod.timespread", "tempmod_tempspread_updatetime", 2, 60, 0)
        panel:ControlHelp("#tempmod.tempmod.timespread_help")
    end)

    spawnmenu.AddToolMenuOption("Utilities", "Temperature Mod", "tempmodclient", "#tempmod.tempmod_clientcategory", "", "", function(panel)
        panel:ClearControls()
        panel:Help("#tempmod.tempmod_clienttitle")
        panel:Help("#tempmod.tempmod_optimizationtitle")
        panel:CheckBox("#tempmod.tempmod_clientglow", "tempmod_glow_enabled")
        panel:ControlHelp("#tempmod.tempmod_clientglowdesc")
        panel:NumSlider("#tempmod.tempmod_clientglowcount", "tempmod_glow_max", 0, 10, 0)
        panel:ControlHelp("#tempmod.tempmod_clientglowdesc2")
	end )

    spawnmenu.AddToolMenuOption("Utilities", "Temperature Mod", "tempmodabout", "#tempmod.tempmod_aboutaddon", "", "", function(panel)
        panel:ClearControls()
        panel:Help("#tempmod.tempmod_abouttempmod")
        panel:Help("#tempmod.tempmod_creatortitle")
        panel:Help("#tempmod.tempmod_testertitle")
        panel:Help("#tempmod.tempmod_codesupporter")

        local workshop = panel:Button("#tempmod.tempmod_workshop")

        workshop.DoClick = function()
            gui.OpenURL("https://steamcommunity.com/sharedfiles/filedetails/?id=3259220540")
        end

        panel:AddItem(workshop)
    end)
end)